export const styles = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    minHeight: '520px',
    backgroundColor: '#131722',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #2A2E39',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Trebuchet MS', Roboto, sans-serif",
    color: '#D1D4DC',
  },
  topHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 16px',
    backgroundColor: '#1E222D',
    borderBottom: '1px solid #2A2E39',
    flexShrink: 0,
    zIndex: 5,
  },
  brandGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  title: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#F0F3FA',
  },
  badge: {
    fontSize: '11px',
    color: '#787B86',
    backgroundColor: '#2A2E39',
    padding: '2px 8px',
    borderRadius: '10px',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  headerBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'transparent',
    border: '1px solid transparent',
    color: '#D1D4DC',
    padding: '6px 12px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
  },
  activeReplayBtn: {
    backgroundColor: '#2962FF',
    color: '#ffffff',
  },
  separator: {
    width: '1px',
    height: '18px',
    backgroundColor: '#2A2E39',
  },
  innerSeparator: {
    width: '1px',
    height: '14px',
    backgroundColor: '#434651',
  },
  dropdownMenu: {
    position: 'absolute' as const,
    top: '36px',
    right: 0,
    width: '180px',
    backgroundColor: '#1E222D',
    border: '1px solid #2A2E39',
    borderRadius: '6px',
    padding: '8px 0',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
    zIndex: 100,
  },
  dropdownTitle: {
    fontSize: '11px',
    color: '#787B86',
    padding: '4px 12px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  dropdownItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  canvasContainer: {
    position: 'relative' as const,
    flex: 1,
    width: '100%',
    height: '100%',
    minHeight: '440px',
    overflow: 'hidden',
  },
  cutBanner: {
    position: 'absolute' as const,
    top: '12px',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 30,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#f23645',
    color: '#ffffff',
    fontSize: '12px',
    fontWeight: 600,
    padding: '6px 16px',
    borderRadius: '20px',
    boxShadow: '0 4px 12px rgba(242, 54, 69, 0.4)',
  },
  legendOverlay: {
    position: 'absolute' as const,
    top: '12px',
    left: '12px',
    zIndex: 10,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  legendRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(30, 34, 45, 0.75)',
    backdropFilter: 'blur(4px)',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    color: '#787B86',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    padding: 0,
  },
  floatingReplayBar: {
    position: 'absolute' as const,
    bottom: '16px',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 20,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: 'rgba(30, 34, 45, 0.95)',
    backdropFilter: 'blur(8px)',
    border: '1px solid #2A2E39',
    borderRadius: '30px',
    padding: '6px 16px',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.6)',
  },
  controlBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    border: 'none',
    backgroundColor: '#2A2E39',
    color: '#F0F3FA',
    cursor: 'pointer',
    padding: 0, // Prevents default padding from pushing SVG out of bounds
    boxSizing: 'border-box' as const, // Ensures width/height are respected perfectly
  },
  speedSelect: {
    backgroundColor: '#2A2E39',
    color: '#D1D4DC',
    border: 'none',
    borderRadius: '4px',
    padding: '4px 6px',
    fontSize: '11px',
    cursor: 'pointer',
  },
  scrubber: {
    width: '120px',
    accentColor: '#2962FF',
    cursor: 'pointer',
  },
};